sudo: required

language: node_js

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker build -t cheshirecode/cheshirecode-next-boilerplate --build-arg NODE_ENV=production --build-arg NODE_IMAGE=8.12.0-alpine .
  - docker run -i cheshirecode/cheshirecode-next-boilerplate du -sh .

script:
  - docker ps -a 