sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t cheshirecode/cheshirecode-next-boilerplate --build-arg NODE_ENV=production --build-arg NODE_IMAGE=8.12.0-alpine .
  - docker run -i cheshirecode/cheshirecode-next-boilerplate yarn count

script:
  - docker ps -a